import { useEffect, useMemo, useState } from "react";
import { Card } from "../Card";
import { useIsMobile } from "../../hooks/useIsMobile";
import { fetchUmbralGacetas, gacetaOfficialUrl } from "../../services/umbralGacetas";
import { BORDER, TEXT, MUTED, ACCENT, font, BG2, BG3 } from "../../constants";
import { WEEKLY_INSTITUTIONAL } from "../../data/weeklyInstitutional";

const colors = { "Designación":"#0468B1", "Jubilación":"#22c55e", "Traslado":"#8b5cf6", "Supresión":"#dc2626", "Reorganización":"#14b8a6", "Revocación":"#f59e0b", "Ley":"#ec4899", "Autorización":"#f97316", "Otro":"#64748b" };

export function TabGacetas() {
  const mob = useIsMobile();
  const [data,setData]=useState(null), [loading,setLoading]=useState(true), [error,setError]=useState(null);
  const [query,setQuery]=useState(""), [type,setType]=useState("Todos"), [military,setMilitary]=useState(false);
  const [selectedDate,setSelectedDate]=useState(null), [gazetteType,setGazetteType]=useState("Todos");
  const [selectedOrganism,setSelectedOrganism]=useState(null), [institutionsOpen,setInstitutionsOpen]=useState(false);
  const [page,setPage]=useState(1), [pageSize,setPageSize]=useState(25);
  useEffect(()=>{ fetchUmbralGacetas().then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false)); },[]);
  const records=data?.records||[];
  const types=["Todos",...new Set(records.map(r=>r.change_label).filter(Boolean))];
  const filtered=useMemo(()=>records.filter(r=>{
    const text=[r.person_name,r.post_or_position,r.organism,r.summary,r.gazette_number].filter(Boolean).join(" ").toLowerCase();
    return (!query||text.includes(query.toLowerCase())) && (type==="Todos"||r.change_label===type) && (gazetteType==="Todos"||r.gazette_type===gazetteType) && (!selectedDate||r.gazette_date===selectedDate) && (!selectedOrganism||r.organism===selectedOrganism) && (!military||r.is_military_person||r.is_military_post);
  }),[records,query,type,gazetteType,selectedDate,selectedOrganism,military]);
  const latestDate=records[0]?.gazette_date;
  const designations=records.filter(r=>r.change_label==="Designación").length;
  const militaryPeople=records.filter(r=>r.is_military_person).length;
  const militaryPosts=records.filter(r=>r.is_military_post).length;
  const militaryDesignationPct=designations?records.filter(r=>r.change_label==="Designación"&&r.is_military_person).length/designations*100:0;
  const organismCount=new Set(records.map(r=>r.organism).filter(Boolean)).size;
  const ordinary=new Set(records.filter(r=>r.gazette_type==="Ordinaria").map(r=>r.gazette_number)).size;
  const extraordinary=new Set(records.filter(r=>r.gazette_type==="Extraordinaria").map(r=>r.gazette_number)).size;
  const daily=Object.entries(records.reduce((acc,r)=>{if(r.gazette_date)acc[r.gazette_date]=(acc[r.gazette_date]||0)+1;return acc;},{})).sort(([a],[b])=>a.localeCompare(b)).map(([date,count])=>({date,count}));
  const typeCounts=Object.entries(records.reduce((acc,r)=>{const key=r.change_label||"Otro";acc[key]=(acc[key]||0)+1;return acc;},{})).sort((a,b)=>b[1]-a[1]);
  const institutionCounts=Object.entries(records.reduce((acc,r)=>{const key=r.organism?.trim();if(key)acc[key]=(acc[key]||0)+1;return acc;},{})).sort((a,b)=>b[1]-a[1]);
  const shownInstitutions=institutionsOpen?institutionCounts:institutionCounts.slice(0,12);
  const maxDaily=Math.max(...daily.map(d=>d.count),1), maxType=Math.max(...typeCounts.map(([,v])=>v),1), maxInstitution=Math.max(...institutionCounts.map(([,v])=>v),1);
  const activityPoints=daily.length>1?daily.map((d,i)=>`${(i/(daily.length-1))*600},${90-(d.count/maxDaily)*82}`).join(" "):"";
  const selectedDayRecords=selectedDate?records.filter(r=>r.gazette_date===selectedDate):[];
  const selectedDaySummary=selectedDate?{
    total:selectedDayRecords.length,
    designations:selectedDayRecords.filter(r=>r.change_label==="Designación").length,
    gazettes:new Set(selectedDayRecords.map(r=>r.gazette_number)).size,
    military:selectedDayRecords.filter(r=>r.is_military_person||r.is_military_post).length,
  }:null;
  const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));
  const safePage=Math.min(page,totalPages);
  const paginatedRecords=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
  useEffect(()=>{setPage(1);},[query,type,gazetteType,selectedDate,selectedOrganism,military,pageSize]);

  if(loading) return <Card><div style={{padding:30,textAlign:"center",color:MUTED,fontFamily:font}}>Consultando el lote activo de Gacetas…</div></Card>;
  return <div style={{display:"flex",flexDirection:"column",gap:12}}>
    <div><div style={{fontSize:16,fontWeight:800,color:TEXT}}>🏛️ Gacetas e Instituciones</div><div style={{fontSize:10,color:MUTED,fontFamily:font}}>Cambios institucionales y designaciones · integración externa de solo lectura</div></div>
    <Card accent="#0468B1">
      <div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"baseline",flexWrap:"wrap",marginBottom:9}}><div style={{fontSize:11,fontWeight:800,color:TEXT}}>Novedades institucionales · {WEEKLY_INSTITUTIONAL.period}</div><div style={{fontSize:8,color:MUTED,fontFamily:font}}>{WEEKLY_INSTITUTIONAL.note}</div></div>
      <div style={{display:"grid",gridTemplateColumns:mob?"1fr":"repeat(5,1fr)",gap:7}}>{WEEKLY_INSTITUTIONAL.items.map(item=><div key={item.title} style={{border:`1px solid ${BORDER}`,borderTop:`3px solid ${item.color}`,padding:"9px 10px",background:BG2}}><div style={{fontSize:7,color:item.color,fontFamily:font,textTransform:"uppercase",fontWeight:800,marginBottom:4}}>{item.type}</div><div style={{fontSize:10,fontWeight:800,color:TEXT,lineHeight:1.25,marginBottom:4}}>{item.title}</div><div style={{fontSize:8,color:MUTED,lineHeight:1.45}}>{item.text}</div></div>)}</div>
    </Card>
    {error&&<Card accent="#dc2626"><div style={{color:"#dc2626",fontSize:11}}>No se pudo consultar la fuente externa: {error}.</div></Card>}
    {!error&&<>
      <div style={{display:"grid",gridTemplateColumns:mob?"repeat(2,1fr)":"repeat(4,1fr)",gap:8}}>{[
        [records.length,"Cambios totales",ACCENT],[ordinary,"Gacetas ordinarias","#0f766e"],[extraordinary,"Gacetas extraordinarias","#8b5cf6"],[designations,"Designaciones","#0468B1"],[militaryPeople,"Personas militares","#ca8a04"],[militaryPosts,"Cargos militares","#f97316"],[`${militaryDesignationPct.toFixed(0)}%`,"Designaciones de militares","#dc2626"],[organismCount,"Organismos identificados","#64748b"]
      ].map(([v,l,c])=><Card key={l} accent={c}><div style={{fontSize:25,fontWeight:900,color:c,fontFamily:font}}>{v}</div><div style={{fontSize:9,color:MUTED,fontFamily:font,textTransform:"uppercase"}}>{l}</div></Card>)}</div>
      <div style={{display:"grid",gridTemplateColumns:mob?"1fr":"1.45fr 1fr",gap:10}}>
        <Card><div style={{fontSize:10,color:TEXT,fontWeight:800,marginBottom:3}}>Actividad diaria</div><div style={{fontSize:8,color:MUTED,fontFamily:font,marginBottom:8}}>Selecciona un punto para ver el detalle y filtrar la tabla</div><svg viewBox="-8 0 616 112" style={{width:"100%",height:150,overflow:"visible"}}><line x1="0" x2="600" y1="90" y2="90" stroke={BORDER}/><polyline points={activityPoints} fill="none" stroke="#0f766e" strokeWidth="2"/><polygon points={`0,90 ${activityPoints} 600,90`} fill="#0f766e" opacity=".08"/>{daily.map((d,i)=>{const x=(i/(daily.length-1))*600,y=90-(d.count/maxDaily)*82,active=selectedDate===d.date;return <g key={d.date} onClick={()=>setSelectedDate(active?null:d.date)} style={{cursor:"pointer"}}><circle cx={x} cy={y} r="9" fill="transparent"/><circle cx={x} cy={y} r={active?6:3.5} fill={active?"#dc2626":"#0f766e"} stroke="#fff" strokeWidth="1.5"/><title>{d.date}: {d.count} cambios</title></g>})}{daily.filter((_,i)=>i===0||i===daily.length-1||i%Math.max(1,Math.floor(daily.length/8))===0).map((d)=><text key={d.date} x={(daily.indexOf(d)/(daily.length-1))*600} y="106" textAnchor="middle" fontSize="8" fill={MUTED}>{new Date(`${d.date}T00:00:00`).toLocaleDateString("es",{month:"short",day:"2-digit"})}</text>)}</svg>{selectedDaySummary?<div style={{display:"grid",gridTemplateColumns:mob?"repeat(2,1fr)":"repeat(4,1fr)",gap:5,padding:"8px",background:"#f0fdfa",border:"1px solid #0f766e30"}}>{[[selectedDate,"Fecha"],[selectedDaySummary.total,"Cambios"],[selectedDaySummary.designations,"Designaciones"],[selectedDaySummary.gazettes,"Gacetas"],[selectedDaySummary.military,"Vínculos militares"]].map(([value,label])=><div key={label} style={{padding:"4px 6px"}}><div style={{fontSize:12,fontWeight:800,color:"#0f766e"}}>{value}</div><div style={{fontSize:7,color:MUTED,fontFamily:font,textTransform:"uppercase"}}>{label}</div></div>)}<button onClick={()=>setSelectedDate(null)} style={{border:"none",background:"transparent",color:"#dc2626",fontSize:8,cursor:"pointer"}}>Quitar fecha ×</button></div>:<div style={{fontSize:8,color:MUTED,fontFamily:font,textAlign:"center",padding:"5px"}}>Pulsa cualquier punto de la línea para consultar esa jornada.</div>}</Card>
        <Card><div style={{fontSize:10,color:TEXT,fontWeight:800,marginBottom:3}}>Composición de Gacetas</div><div style={{fontSize:8,color:MUTED,fontFamily:font,marginBottom:10}}>Selecciona un tipo para filtrar los registros</div><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:18,marginTop:12}}><button onClick={()=>setGazetteType("Todos")} title="Mostrar todos" style={{width:110,height:110,padding:0,border:gazetteType==="Todos"?`3px solid ${ACCENT}`:"3px solid transparent",borderRadius:"50%",background:`conic-gradient(#0f766e 0 ${(ordinary/(ordinary+extraordinary))*100}%, #8b5cf6 0)`,position:"relative",cursor:"pointer"}}><span style={{position:"absolute",inset:18,borderRadius:"50%",background:BG2,display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,fontWeight:900,color:TEXT}}>{ordinary+extraordinary}</span></button><div style={{fontSize:10,lineHeight:2}}><button onClick={()=>setGazetteType(gazetteType==="Ordinaria"?"Todos":"Ordinaria")} style={legendButton(gazetteType==="Ordinaria")}><span style={{color:"#0f766e"}}>●</span> Ordinarias <b>{ordinary}</b></button><button onClick={()=>setGazetteType(gazetteType==="Extraordinaria"?"Todos":"Extraordinaria")} style={legendButton(gazetteType==="Extraordinaria")}><span style={{color:"#8b5cf6"}}>●</span> Extraordinarias <b>{extraordinary}</b></button></div></div></Card>
      </div>
      <Card><div style={{fontSize:10,color:TEXT,fontWeight:800,marginBottom:3}}>Tipos de cambio institucional</div><div style={{fontSize:8,color:MUTED,fontFamily:font,marginBottom:10}}>Selecciona una barra para filtrar la tabla</div><div style={{display:"grid",gridTemplateColumns:mob?"1fr":"1fr 1fr",gap:"7px 18px"}}>{typeCounts.map(([label,count])=><button onClick={()=>setType(type===label?"Todos":label)} key={label} style={{display:"grid",gridTemplateColumns:"95px 1fr 38px",gap:7,alignItems:"center",border:type===label?`1px solid ${colors[label]||ACCENT}`:"1px solid transparent",background:type===label?`${colors[label]||ACCENT}0d`:"transparent",padding:"3px",cursor:"pointer",textAlign:"left"}}><span style={{fontSize:9,color:colors[label]||TEXT,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis",fontWeight:type===label?800:500}}>{label}</span><span style={{height:8,background:"#e7ebf0",borderRadius:4,overflow:"hidden"}}><span style={{display:"block",height:"100%",width:`${count/maxType*100}%`,background:colors[label]||"#64748b"}}/></span><b style={{fontSize:9,color:TEXT,textAlign:"right"}}>{count}</b></button>)}</div></Card>
      <Card>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:8,flexWrap:"wrap",marginBottom:9}}><div><div style={{fontSize:10,color:TEXT,fontWeight:800}}>Distribución por instituciones</div><div style={{fontSize:8,color:MUTED,fontFamily:font}}>Selecciona una institución para filtrar sus cambios y designaciones</div></div>{institutionCounts.length>12&&<button onClick={()=>setInstitutionsOpen(v=>!v)} style={{border:`1px solid ${BORDER}`,background:BG2,color:ACCENT,padding:"5px 8px",fontSize:8,cursor:"pointer"}}>{institutionsOpen?"Mostrar principales ▲":`Ver todas (${institutionCounts.length}) ▼`}</button>}</div>
        <div style={{display:"grid",gridTemplateColumns:mob?"1fr":"1fr 1fr",gap:"6px 18px"}}>{shownInstitutions.map(([label,count])=><button key={label} onClick={()=>setSelectedOrganism(selectedOrganism===label?null:label)} title={label} style={{display:"grid",gridTemplateColumns:mob?"130px 1fr 34px":"minmax(150px,220px) 1fr 38px",gap:7,alignItems:"center",border:selectedOrganism===label?`1px solid ${ACCENT}`:"1px solid transparent",background:selectedOrganism===label?`${ACCENT}0d`:"transparent",padding:"4px",cursor:"pointer",textAlign:"left"}}><span style={{fontSize:8,color:selectedOrganism===label?ACCENT:TEXT,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis",fontWeight:selectedOrganism===label?800:500}}>{label}</span><span style={{height:9,background:"#e7ebf0",borderRadius:4,overflow:"hidden"}}><span style={{display:"block",height:"100%",width:`${count/maxInstitution*100}%`,background:selectedOrganism===label?ACCENT:"#64748b"}}/></span><b style={{fontSize:9,color:TEXT,textAlign:"right"}}>{count}</b></button>)}</div>
        {selectedOrganism&&<div style={{marginTop:8,padding:"6px 8px",background:"#eff6ff",border:`1px solid ${ACCENT}30`,fontSize:8,color:TEXT,fontFamily:font}}>Institución seleccionada: <b style={{color:ACCENT}}>{selectedOrganism}</b> · {filtered.length} registros visibles <button onClick={()=>setSelectedOrganism(null)} style={{border:"none",background:"transparent",color:"#dc2626",fontSize:8,cursor:"pointer"}}>Quitar filtro ×</button></div>}
      </Card>
      <Card><div style={{display:"flex",gap:7,flexWrap:"wrap",alignItems:"center"}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar persona, cargo u organismo…" style={{flex:"1 1 240px",padding:"8px 10px",border:`1px solid ${BORDER}`,fontSize:11}}/><select value={type} onChange={e=>setType(e.target.value)} style={{padding:"8px",border:`1px solid ${BORDER}`,fontSize:10}}>{types.map(t=><option key={t}>{t}</option>)}</select><label style={{fontSize:10,color:TEXT,fontFamily:font}}><input type="checkbox" checked={military} onChange={e=>setMilitary(e.target.checked)}/> Solo militar</label><span style={{fontSize:9,color:MUTED,fontFamily:font}}>{filtered.length} resultados</span>{(selectedDate||selectedOrganism||gazetteType!=="Todos"||type!=="Todos"||military||query)&&<button onClick={()=>{setSelectedDate(null);setSelectedOrganism(null);setGazetteType("Todos");setType("Todos");setMilitary(false);setQuery("");}} style={{border:`1px solid ${BORDER}`,background:BG2,color:ACCENT,padding:"6px 9px",fontSize:9,cursor:"pointer"}}>Limpiar selección</button>}</div>{(selectedDate||selectedOrganism||gazetteType!=="Todos"||type!=="Todos")&&<div style={{display:"flex",gap:5,flexWrap:"wrap",marginTop:7,fontSize:8,fontFamily:font,color:MUTED}}>Filtros gráficos: {selectedDate&&<b>{selectedDate}</b>}{selectedOrganism&&<b>{selectedOrganism}</b>}{gazetteType!=="Todos"&&<b>{gazetteType}</b>}{type!=="Todos"&&<b>{type}</b>}</div>}</Card>
      <Card style={{padding:0,overflow:"hidden"}}>
        <PaginationControls page={safePage} totalPages={totalPages} pageSize={pageSize} total={filtered.length} onPage={setPage} onPageSize={setPageSize}/>
        <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:mob?760:900}}><thead><tr>{["Fecha / Gaceta","Cambio","Persona / cargo","Organismo","Síntesis","Fuente"].map(h=><th key={h} style={{padding:"8px 9px",textAlign:"left",fontSize:8,color:MUTED,fontFamily:font,textTransform:"uppercase",borderBottom:`1px solid ${BORDER}`}}>{h}</th>)}</tr></thead><tbody>{paginatedRecords.map(r=><tr key={r.id}><td style={cell()}><b>{r.gazette_date}</b><br/><span style={{color:MUTED}}>N.º {r.gazette_number}</span></td><td style={cell()}><span style={{color:colors[r.change_label]||MUTED,fontWeight:700}}>{r.change_label}</span>{(r.is_military_person||r.is_military_post)&&<div style={{fontSize:8,color:"#ca8a04"}}>⚔ componente militar</div>}</td><td style={cell()}><b>{r.person_name||r.institution||"—"}</b><br/><span style={{color:MUTED}}>{r.post_or_position||""}</span></td><td style={cell()}>{r.organism||"—"}</td><td style={{...cell(),maxWidth:310}}>{r.summary||"—"}</td><td style={cell()}><a href={gacetaOfficialUrl(r.gazette_number)} target="_blank" rel="noreferrer" style={{color:ACCENT}}>Gaceta ↗</a></td></tr>)}</tbody></table></div>
        <PaginationControls page={safePage} totalPages={totalPages} pageSize={pageSize} total={filtered.length} onPage={setPage} onPageSize={setPageSize} compact/>
      </Card>
      <div style={{fontSize:8,color:MUTED,fontFamily:font,textAlign:"center"}}>Fuente primaria enlazada: Gaceta Oficial · lote actualizado {data.batchUpdatedAt?new Date(data.batchUpdatedAt).toLocaleString("es"):"—"} · último registro {latestDate||"—"}.</div>
    </>}
  </div>;
}
const cell=()=>({padding:"8px 9px",fontSize:9,color:TEXT,verticalAlign:"top",borderBottom:`1px solid ${BORDER}` ,lineHeight:1.4});
const legendButton=active=>({display:"block",width:"100%",border:active?`1px solid ${ACCENT}`:"1px solid transparent",background:active?`${ACCENT}0d`:"transparent",padding:"2px 5px",fontSize:10,textAlign:"left",cursor:"pointer",color:TEXT});
const PaginationControls=({page,totalPages,pageSize,total,onPage,onPageSize,compact=false})=><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:8,flexWrap:"wrap",padding:compact?"8px 10px":"10px",background:BG3,borderBottom:compact?"none":`1px solid ${BORDER}`,borderTop:compact?`1px solid ${BORDER}`:"none"}}>
  <div style={{fontSize:8,color:MUTED,fontFamily:font}}>Página <b style={{color:TEXT}}>{page}</b> de <b style={{color:TEXT}}>{totalPages}</b> · {total} registros</div>
  <div style={{display:"flex",alignItems:"center",gap:6}}>
    {!compact&&<label style={{fontSize:8,color:MUTED,fontFamily:font}}>Filas <select value={pageSize} onChange={e=>onPageSize(Number(e.target.value))} style={{marginLeft:4,padding:"4px 6px",border:`1px solid ${BORDER}`,background:BG2,fontSize:8}}><option value={10}>10</option><option value={25}>25</option><option value={50}>50</option></select></label>}
    <button disabled={page<=1} onClick={()=>onPage(p=>Math.max(1,p-1))} style={pageButton(page<=1)}>← Anterior</button>
    <button disabled={page>=totalPages} onClick={()=>onPage(p=>Math.min(totalPages,p+1))} style={pageButton(page>=totalPages)}>Siguiente →</button>
  </div>
</div>;
const pageButton=disabled=>({border:`1px solid ${BORDER}`,background:disabled?BG3:BG2,color:disabled?MUTED:ACCENT,padding:"5px 9px",fontSize:8,fontFamily:font,cursor:disabled?"not-allowed":"pointer",borderRadius:3});
