import { useState } from "react";
import { Card } from "./Card";
import { EARTHQUAKE_HISTORY, EARTHQUAKE_MILESTONES } from "../data/earthquakeHistory";
import { BORDER, TEXT, MUTED, ACCENT, font } from "../constants";

const views={ deaths:{label:"Fallecidos",field:"deaths",color:"#dc2626"}, injured:{label:"Heridos",field:"injured",color:"#f97316"}, camps:{label:"Personas en campamentos",field:"campPeople",color:"#7c3aed"} };
const formatNumber=value=>value==null?"No publicado":new Intl.NumberFormat("es-VE").format(value);

export function EarthquakeEvolution({ mob=false }) {
  const [view,setView]=useState("deaths");
  const cfg=views[view];
  const max=Math.max(...EARTHQUAKE_HISTORY.map(d=>d[cfg.field]).filter(v=>v!=null),1);
  return <div style={{ display:"flex", flexDirection:"column", gap:12 }}>
    <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", gap:10, flexWrap:"wrap" }}><div><div style={{ fontSize:15, fontWeight:800, color:TEXT }}>Evolución de la emergencia sísmica</div><div style={{ fontSize:10, color:MUTED, fontFamily:font }}>24 de junio–14 de agosto de 2026 · balances recopilados en S24–S31</div></div><div style={{ display:"flex", border:`1px solid ${BORDER}` }}>{Object.entries(views).map(([id,item])=><button key={id} onClick={()=>setView(id)} style={{ border:"none", padding:"6px 9px", background:view===id?item.color:"transparent", color:view===id?"#fff":MUTED, fontFamily:font, fontSize:9, cursor:"pointer" }}>{item.label}</button>)}</div></div>
    <Card><div style={{ fontSize:10, color:MUTED, fontFamily:font, textTransform:"uppercase", marginBottom:14 }}>{cfg.label} · evolución de balances publicados</div><div style={{ display:"flex", alignItems:"flex-end", height:190, gap:mob?6:16, padding:"0 8px" }}>{EARTHQUAKE_HISTORY.map(d=>{const value=d[cfg.field];const height=value==null?5:Math.max(12,value/max*145);return <div key={d.date} style={{ flex:1, display:"flex", flexDirection:"column", alignItems:"center", gap:5 }}><div style={{ fontSize:mob?8:10, color:value==null?MUTED:cfg.color, fontWeight:700, textAlign:"center" }}>{value==null?"s/d":formatNumber(value)}</div><div style={{ width:"100%", maxWidth:74, height, background:value==null?"repeating-linear-gradient(45deg,#e5e7eb,#e5e7eb 4px,#f8fafc 4px,#f8fafc 8px)":cfg.color, opacity:value==null?.8:.82, borderRadius:"3px 3px 0 0", border:value==null?`1px dashed ${BORDER}`:"none" }}/><div style={{ fontSize:8, color:MUTED, fontFamily:font, textAlign:"center", minHeight:22 }}>{d.date}<br/>{d.period.split("·")[0]}</div></div>})}</div><div style={{ fontSize:9, color:MUTED, marginTop:10 }}>Las barras rayadas indican que la variable no fue publicada en ese corte; no representan cero.</div></Card>
    <div style={{ display:"grid", gridTemplateColumns:mob?"1fr":"1.2fr .8fr", gap:12 }}>
      <Card><div style={{ fontSize:10, color:MUTED, fontFamily:font, textTransform:"uppercase", marginBottom:10 }}>Serie consolidada</div><div style={{ overflowX:"auto" }}><table style={{ width:"100%", borderCollapse:"collapse", fontSize:10 }}><thead><tr>{["Corte","Fallecidos","Heridos","Campamentos","Personas alojadas","Viviendas afectadas","Escombros"].map(h=><th key={h} style={{ padding:"6px", textAlign:"left", color:MUTED, fontFamily:font, borderBottom:`1px solid ${BORDER}`, whiteSpace:"nowrap" }}>{h}</th>)}</tr></thead><tbody>{EARTHQUAKE_HISTORY.map(d=><tr key={d.date}><td style={{ padding:"7px 6px", borderBottom:`1px solid ${BORDER}` }}><b>{d.date}</b></td><td style={{ padding:6 }}>{formatNumber(d.deaths)}</td><td style={{ padding:6 }}>{formatNumber(d.injured)}</td><td style={{ padding:6 }}>{formatNumber(d.camps)}</td><td style={{ padding:6 }}>{formatNumber(d.campPeople)}</td><td style={{ padding:6 }}>{formatNumber(d.homesAffected)}</td><td style={{ padding:6 }}>{d.rubble==null?"No publicado":`${d.rubble}%`}</td></tr>)}</tbody></table></div></Card>
      <Card><div style={{ fontSize:10, color:MUTED, fontFamily:font, textTransform:"uppercase", marginBottom:10 }}>Hitos</div>{EARTHQUAKE_MILESTONES.map((m,index)=><div key={m.date} style={{ display:"grid", gridTemplateColumns:"48px 12px 1fr", gap:7, paddingBottom:10 }}><div style={{ fontSize:9, color:ACCENT, fontFamily:font, fontWeight:700 }}>{m.date}</div><div style={{ position:"relative" }}><span style={{ display:"block", width:8, height:8, borderRadius:"50%", background:index===EARTHQUAKE_MILESTONES.length-1?"#dc2626":ACCENT, marginTop:2 }}/>{index<EARTHQUAKE_MILESTONES.length-1&&<span style={{ position:"absolute", width:1, background:BORDER, top:11, bottom:-10, left:3.5 }}/>}</div><div><div style={{ fontSize:11, fontWeight:700 }}>{m.title}</div><div style={{ fontSize:9, color:MUTED, lineHeight:1.45, marginTop:2 }}>{m.text}</div></div></div>)}</Card>
    </div>
    <div style={{ background:"#fff7ed", border:"1px solid #fdba7466", padding:"10px 13px", fontSize:10, color:"#9a3412", lineHeight:1.55 }}><b>Ruptura de comparabilidad:</b> el balance del 3 de agosto deja de informar heridos, campamentos y personas alojadas, y comienza a enfatizar viviendas afectadas y retiro de escombros. Los vacíos se conservan como “no publicado”.</div>
  </div>;
}
